# Ref: https://supabase.com/docs/guides/local-development/cli/config

project_id = "tasks-app"

[api]
# Enable / disable PostgREST
# https://docs.postgrest.org/en/v12/
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

# Enable / disable PgBouncer conn pooler
[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.seed]
# If enabled, seeds the database after migrations during a db reset.
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

# Email testing server
[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

# Uncomment to configure local storage buckets
# [storage.buckets.images]
# public = false
# file_size_limit = "50MiB"
# allowed_mime_types = ["image/png", "image/jpeg"]
# objects_path = "./images"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = false

[auth.email]
enable_signup = false

[auth.sms]
enable_signup = false

# Edge functions for supabase
[edge_runtime]
enabled = false

# Supabase analytics. Keep this on for local analytics
[analytics]
enabled = true
port = 54327
backend = "postgres"
