services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'copilot'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
