services:
  postgres:
    image: postgres:15-alpine
    ports:
      - $DATABASE_PORT:5432
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
