'use client'

export { default as TodoIcon } from './todo.svg'
export { default as InprogressIcon } from './inprogress.svg'
export { default as InreviewIcon } from './inreview.svg'
export { default as DoneIcon } from './done.svg'
export { default as HumansIcon } from './humans.svg'
export { default as AttachmentIcon } from './attachment.svg'
export { default as PdfIcon } from './pdf.svg'
export { default as PngIcon } from './png.svg'
export { default as CancelFilledIcon } from './cancel-filled.svg'
export { default as CalenderIcon } from './calendar-edit.svg'
export { default as SearchIcon } from './search.svg'
export { default as FilterByAsigneeIcon } from './filterAssignee.svg'
export { default as CrossIcon } from './cross.svg'
export { default as TrashIcon } from './trash.svg'
export { default as PlusIcon } from './plus.svg'
export { default as TemplateIcon } from './template.svg'
export { default as EditIcon } from './edit.svg'
export { default as BoardViewIcon } from './board-view.svg'
export { default as ListViewIcon } from './list-view.svg'
