import {
  AviIcon,
  CsvIcon,
  DocIcon,
  CompletedIcon,
  InProgressIcon,
  XlxIcon,
  InreviewIcon,
  JpgIcon,
  MovIcon,
  Mp4Icon,
  PdfIcon,
  PngIcon,
  SvgIcon,
  TodoIcon,
  ZipIcon,
  IsoIcon,
  TxtIcon,
  GifIcon,
  Mp3Icon,
  TodoIconSmall,
  InProgressIconSmall,
  CompletedIconSmall,
  InreviewIconSmall,
  InreviewIconMedium,
  DefaultFileIcon,
  PngIconSmall,
  PdfIconSmall,
  SvgIconSmall,
  CsvIconSmall,
  ZipIconSmall,
  DocIconSmall,
  AviIconSmall,
  JpgIconSmall,
  MovIconSmall,
  Mp4IconSmall,
  XlxIconSmall,
  IsoIconSmall,
  TxtIconSmall,
  GifIconSmall,
  Mp3IconSmall,
  DefaultFileIconSmall,
} from '@/icons'
import { WorkflowState } from '@/types/dto/workflowStates.dto'
import { Sizes } from '@/types/interfaces'

import { ReactNode } from 'react'

export const statusIcons: { [key in Exclude<Sizes, Sizes.LARGE>]: { [key in WorkflowState]: ReactNode } } = {
  medium: {
    backlog: <TodoIcon />,
    unstarted: <TodoIcon />,
    started: <InProgressIcon />,
    completed: <CompletedIcon />,
    cancelled: <InreviewIconMedium />,
  },
  small: {
    backlog: <TodoIconSmall />,
    unstarted: <TodoIconSmall />,
    started: <InProgressIconSmall />,
    completed: <CompletedIconSmall />,
    cancelled: <InreviewIconSmall />,
  },
}

export const attachmentIcons: { [key: string]: ReactNode } = {
  'image/png': <PngIcon />,
  'application/pdf': <PdfIcon />,
  'image/svg+xml': <SvgIcon />,
  'text/csv': <CsvIcon />,
  'application/zip': <ZipIcon />,
  'application/msword': <DocIcon />,
  'video/vnd.avi': <AviIcon />,
  'image/jpeg': <JpgIcon />,
  'video/quicktime': <MovIcon />,
  'video/mp4': <Mp4Icon />,
  'application/vnd.ms-excel': <XlxIcon />,
  'application/vnd.efi.iso': <IsoIcon />,
  'text/plain': <TxtIcon />,
  'image/gif': <GifIcon />,
  'audio/mpeg': <Mp3Icon />,
  default: <DefaultFileIcon />,
}

export const attachmentIconsSmall: { [key: string]: ReactNode } = {
  'image/png': <PngIconSmall />,
  'application/pdf': <PdfIconSmall />,
  'image/svg+xml': <SvgIconSmall />,
  'text/csv': <CsvIconSmall />,
  'application/zip': <ZipIconSmall />,
  'application/msword': <DocIconSmall />,
  'video/vnd.avi': <AviIconSmall />,
  'image/jpeg': <JpgIconSmall />,
  'video/quicktime': <MovIconSmall />,
  'video/mp4': <Mp4IconSmall />,
  'application/vnd.ms-excel': <XlxIconSmall />,
  'application/vnd.efi.iso': <IsoIconSmall />,
  'text/plain': <TxtIconSmall />,
  'image/gif': <GifIconSmall />,
  'audio/mpeg': <Mp3IconSmall />,
  default: <DefaultFileIconSmall />,
}
